### ISSUE TITLE
Current state is very unstable

### ISSUE THREAD

**Issue by borisrorsvort** [jsaulou/vscode-theme-by-language#1]
A few issues I noticed,

- It take a while to swtich, so the experience it not ideal
- dunno if just me, but I can’t change the main theme again, it changes it to some random one when browsing files

**Comment by jsaulou** [comment]
Thank you for your feedback.

- I don't if much can be done to improve the switch speed but I'll take a look.
- Have you defined the default theme using the command "Set default theme"? I think there is an issue if this not done. I will check that also.

**Comment by borisrorsvort** [comment]
I figured out what was the problem:
Basically when you set a theme say for markdown, it also copy `workbench.colorTheme` to the custom config (the "*"): 

```
"theme-by-language.themes": {
    "*": "Cyberpunk",
    "markdown": "Kary Pro Colors － Eye Light"
  },
```
But if you try changing the main theme via «Set default theme» it doesn’t update the current config.
My suggestion would be to default to `workbench.colorTheme` instead of copying the default.

**Comment by jsaulou** [comment]
The `workbench.colorTheme` is copied if the `"*"` does not exist. This is to remember what theme you used. And this theme will be used as the default theme.

When you change the default theme, it changes the `"*"`  and then applies the theme for the current file language. If the current file language has a custom theme, this is the one that will be applied. The idea is you can set the default theme when viewing say a markdown file that uses a custom theme. Changing the default theme does not change the theme for markdown and when the default theme is changed, the custom theme is then applied back.

Do you think changing the default theme should also change the theme for the current file language?
Does it feel more natural to you? Is this what you would expect?

**Comment by borisrorsvort** [comment]
Well that’s the problem, on osx at least (just tested multiple times) if you change the `workbench.colorTheme` when "*" is already set, it doesn’t update "*".

**Comment by jsaulou** [comment]
Do you mean changing `workbench.colorTheme` in the User Settings file or by using the standard vscode theme selection?
That will not work indeed. You have to use the 'Set default theme' command to change the `"*"`.

The reason is the `workbench.colorTheme` is used to change the current theme and it will change for previewing themes for instance when settings the default or current file language. I would need to be able to know what caused the `workbench.colorTheme` to change and I don't know if that is possible.

If you have ideas or if I misunderstood, let me know.

**Comment by borisrorsvort** [comment]
Ok I didn’t notice the note in the readme, sorry about the confusion.
I would suggest to add the note within the «How to use section» in the readme. Split in 2 subtitles:

- Set default theme fallback
- Set custom theme for a filetype

**Comment by jsaulou** [comment]
No worries. I will update the README.
Thank you for your feedback.
