### ISSUE TITLE
Ability to modify color parameters for a theme

### ISSUE THREAD

**Issue by RobFosterNYC** [jsaulou/vscode-theme-by-language#11]
I looked inside the settings.json in VS-Code and I did not see the Theme Name and the list of colors its currently using when I have a theme. Im currently using Expressive Theme for C++ language.....
But cant find the colors list to modify the colors a bit to how I want them for C++ particular theme.
I dont know if this extension does write to the settings.json file with a list of colors that its
currently using for the current them, so people can modify it if they need to.
.
A long time ago I seen theme name and a list of colors its using for each part of the theme.
But now I cant find either the file I got it from or location, or if it was the extension that did it or not.
Anyways here is an example of several themes I have modified.  But this was a while ago,
And I forgot how I first got the colors list....  sorry its a bit confusing, but anyways, here is a pic.

.
![Screenshot_3](https://user-images.githubusercontent.com/18384135/70647969-1c6e3980-1c18-11ea-96e2-c1c22278c3cf.png)

**Comment by jsaulou** [comment]
The extension writes something like this in `settings.json`:

```json
"theme-by-language.themes": {
  "*": "Ayu Light",
  "jsonc": "Default Dark+",
  "ini": "Ayu Mirage",
  "shellscript": "Abyss"
}
```

And it only changes the `workbench.colorTheme` to change theme.

Hope that helps.

**Comment by RobFosterNYC** [comment]
hmm, now im wondering where I got the colors list for each theme I used....lol

**Comment by RobFosterNYC** [comment]
Is it possible that you can make your extension place all the colors of a theme chosen by the user
in the settings , like shown in the pictures provided.  I think that would be really cool :)
Basically it would read the theme colors used in the theme, then it would make the list of colors,
in the settings.json file  at the bottom of the settings view.

Just curiously asking 💃

**Comment by jsaulou** [comment]
I'm not sure if it's possible and even desired.
The goal of the extension is to switch the theme, not really to customize them.

You can have a look at [here](https://github.com/Microsoft/vscode/issues/20652#issuecomment-410626650), maybe that is what you're looking for. The whole issue might interest you but the main point is the `Generate color theme from current settings` command for you.

**Comment by jsaulou** [comment]
I experimented with reading the theme colors and adding them the settings.json file but it was hacky and very slow.  
I'm closing the issue because I don't think this is doable or the purpose of this extension.
