### ISSUE TITLE
Set fonts based on language

### ISSUE THREAD

**Issue by aavetis** [jsaulou/vscode-theme-by-language#16]
Is it possible to also change the font when changing the theme for certain languages?

example: switching between code (mono font) and markdown (sans serif)

**Comment by jsaulou** [comment]
AFAIK, the font is not linked to the theme. But you can set a font for a specific language in your user settings. Maybe this is what you want. 

Here is an example to use "Courier New" for markdown files.

```json
"[markdown]": {
  "editor.fontFamily": "'Courier New'"
}
```

**Comment by aavetis** [comment]
thanks; solved
