### ISSUE TITLE
Ability to update global settings, not workspace

### ISSUE THREAD

**Issue by DifficultNick** [jsaulou/vscode-theme-by-language#18]
Problem: I need to publish `.vscode/settings.json` file in my repo for some reasons, so I always have changes of     `workbench.colorTheme` in it cause I use your cool extension =)

It would be great to have some configuration (for example, `theme-by-language.useGlobalConfigOnly`) that will update only `vscode.ConfigurationTarget.Global`

**Comment by jsaulou** [comment]
This is a good setting idea. I know it can be very annoying to deal with changes in versioned settings file 😊

As a workaround for now, you can manually edit your user settings file. Just copy paste what was added in your workspace settings file. The UI does nothing more than editing the settings files.

**Comment by DifficultNick** [comment]
If I understood you correctly, this workarouтd doesn't work.
Here my user settings:
```json
"theme-by-language.themes": {
	"*": "Default Dark+",
	"myLang": "MyTheme"
},
"workbench.colorTheme": "Default Dark+"
```
but when I switch to `myLang` file and back to any other file, I see `"workbench.colorTheme": "Default Dark+"` in my workspace settings.

**Comment by jsaulou** [comment]
Oh sorry you're right, I didn't think of that.

**Comment by EnderShadow8** [comment]
@jsaulou What is the status of this issue?

**Comment by DifficultNick** [comment]
@jsaulou, I've created a PR. Please, take a look and approve if everything is ok

**Comment by DifficultNick** [comment]
@jsaulou, so how about this?)

**Comment by silkfire** [comment]
@jsaulou Would it be possible to assign someone extra to maintain this wonderful extension if you feel that you don't have the time or interest in continuing to do so? I'd love for this PR to be merged as soon as possible. 🙏🏻

**Comment by jsaulou** [comment]
Thank you @DifficultNick for the PR!
