### ISSUE TITLE
different themes for jupyter notebook and `.py` file

### ISSUE THREAD

**Issue by wkerzendorf** [jsaulou/vscode-theme-by-language#20]
It seems that if I set the theme for a "Language" then it affects all files with that "language". This is a downside specifically for jupyter notebooks that can contain multiple languages. Is it possible to set the theme by filetype?

Thanks for providing this open source tool - very nice!

**Comment by droumis** [comment]
This would be a huge improvement. +1

**Comment by jonsedar** [comment]
Just found this extension when looking for exactly this functionality: to theme Jupyter notebooks differently from sourcefiles. 

Is it doable to theme by filename rather than language?

**Comment by wiseyoungbuck** [comment]
This is the exact feature I need. I am addicted to my notebooks looking like traditional notesbooks.

**Comment by jsaulou** [comment]
Closing in favor of #24.
