### ISSUE TITLE
Difference between .py and .ipybn

### ISSUE THREAD

**Issue by Juancho-Coding** [jsaulou/vscode-theme-by-language#21]
Greetings, first of all, thanks a lot, this extension has been really helpful.

I have a question, how can I differentiate the python theme and the jupyter notebook theme. I'm having a hard time because these two types of file work the same theme, is there any tweak I can do to diferentiate them?

Thanks

**Comment by droumis** [comment]
this would be a huge improvement. +1

**Comment by jsaulou** [comment]
Closing in favor of #24.
