### ISSUE TITLE
Allow to set theme based on filename

### ISSUE THREAD

**Issue by jsaulou** [jsaulou/vscode-theme-by-language#24]
I am creating this issue to regroup issues #8, #15, #20, #21. Thank you to everyone who took the time to submit these.
It seems all these issue can be resolved by allowing to set the theme based on the filename.

The implementation could look something like this:

```json
"theme-by-language.themes": {
  "*": "Minone",
  "markdown": "Visual Studio Dark",
  "filename:.*\\.ipynb": "<theme name>",
  "filename:.*\\.drawio": "<theme name>",
},
```

Entries starting with `filename:` would take precedence over other entries.
`filename:` would be followed by a regex to match the filename.

As a first implementation, there would be no UI to do this. Changes would have to be made in the `settings.json` file manually.

I would like to have your opinion and feedback on this in case I'm missing something or you have better ideas.

**Comment by shauld** [comment]
This sounds like a good solution to me.
I am a complete novice with Visual Studio and all it took was a quick search to discover how to access settings.json that once done made the potential implementation of this straightforward.

**Comment by quarkquartet** [comment]
Could be a huge improvement if this is implemented. I really want to distinguish .ipynb and .py.

**Comment by CarlosLopezElorduy** [comment]
I agree with everyone that this would be very useful indeed! :muscle:

**Comment by jsaulou** [comment]
Hey all !

Finally made the changes in `v1.3.0`. Sorry for taking so long to look into it.

**Comment by jonsedar** [comment]
Hey, that's great - thank you so much! I'll look forward to trying out the new changes soon :)
