### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by arbhardwaj98** [jsaulou/vscode-theme-by-language#27]
When I try to run the commands, I get the error shown in the image. If I add the themes in settings.json, nothing happens.

![image](https://github.com/jsaulou/vscode-theme-by-language/assets/30552904/4851c94f-bfe6-45d4-8863-4e4f3dafef3f)

Some details:
OS: Ubuntu 20.04
VSCode version: 1.84.2
Extension version: 1.3.0

**Comment by arbhardwaj98** [comment]
The solution was to install javascript, remove the extension, delete the extension folder from `~/.vscode/extensions/` and reinstall the extension.

**Comment by jsaulou** [comment]
Wow good job finding the solution. Not an obvious one.

I have no idea why you had to manually delete the extension. Was it a first installation or an update?

Anyway, weird issue but happy you got it fixed :)
