### ISSUE TITLE
Opening VSCode to file type doesn't apply set theme...

### ISSUE THREAD

**Issue by chilidad** [jsaulou/vscode-theme-by-language#3]
Windows OS...
Custom theme set to ".java" file type
Opening myfile.java via command prompt, or by shortcut only displays the default theme. Correct them applies only when de-focusing and re-focusing myfile.java in vscode explorer.

How do I make your extension refresh as soon as VSCode opens so that the correct theme gets applied to whatever file I opened from outside VSCode?

**Comment by jsaulou** [comment]
Thanks for the feedback.

I think this may have to do with when custom themes are applied. Right now, I check for `window.onDidChangeActiveTextEditor()`. It is possible that when vscode is opened, the extension is not yet activated and does not receive the event. Maybe the extension should check the current file when activated. I'll take a look.

**Comment by jsaulou** [comment]
Indeed, when the extension is activated, it did not receive the event for `window.onDidChangeActiveTextEditor()`.
When activated, the extension now checks the active editor.

**Comment by chilidad** [comment]
Julien,

Thanks for fixing this. It works as expected now!

-Chris

________________________________
