### ISSUE TITLE
'Set theme for current file language' not working in VS Code 1.28.1

### ISSUE THREAD

**Issue by queeniema** [jsaulou/vscode-theme-by-language#4]
Doesn't seem to work at all. I tried setting the theme for JSON files to 'Kimbie Dark', but nothing happens...

**Comment by jsaulou** [comment]
Hello, it is working for me with version 1.28.1.

Are you using the "Set theme for current file language" command or the standard Color Theme selector of VS Code?
You must use the "Set theme for current file language" command when using the extension and set the default theme to use using the command "Set default theme".

**Comment by queeniema** [comment]
Yes, I was using `Set theme for current file language` on a JSON file... is there a way to see if there's any errors?

**Comment by queeniema** [comment]
Thanks for your help! I had another extension that was modifying `workbench.colorTheme` that seemed to cause some conflicts. Removed that and it works now!
