### ISSUE TITLE
Support for VS2017

### ISSUE THREAD

**Issue by mzhukovs** [jsaulou/vscode-theme-by-language#7]
Any chance you'd tackle making a VS2017 compatible version of this extension?

Or is there one that is similar that already exists that anybody knows about? please share.

Thanks!

**Comment by jsaulou** [comment]
By VS2017, do you mean Visual Studio 2017?
If so, I do not use Visual Studio so no I won't be making a Visual Studio version of this extension.

**Comment by mzhukovs** [comment]
Yes, visual studio. Ok sad to hear that, but great extension, thanks.
