### ISSUE TITLE
Allow custom theme for Jupyter Notebook Preview (and other previews, like Markdown)

### ISSUE THREAD

**Issue by AlexFiliakov** [jsaulou/vscode-theme-by-language#8]
I like my default VSCode theme to be dark, but this becomes problematic for Jupyter Notebooks (https://code.visualstudio.com/docs/python/jupyter-support), which have charts and tables that expect a light background. This currently results in dark-on-dark text that's impossible to read.

I looked to "Theme by language" for an alternative, but it currently doesn't support setting a default theme for Jupyter Notebook Preview because the Preview doesn't have an associated language.

I suspect a similar issue exists for Markdown Preview.

Could we support theme tracking at least for Jupyter Preview?

**Comment by jsaulou** [comment]
Hi,
I have no experience with Jupyter Notepook in VS Code but I will take a look to see what can be done to make it work.

As for previews in general, it might not be desirable actually to use this extension because it changes the whole theme of the editor and previews are usually opened on the side. The result would not be very useful I think. Let me know what you think.

**Comment by ggojedap** [comment]
Thank you for this extension. Yes please, not an issue but a feature request: add support to set a different theme for .ipynb. Jupyter notebooks do not look ok with dark themes.

**Comment by sanjarcode** [comment]
> Thank you for this extension. Yes please, not an issue but a feature request: add support to set a different theme for .ipynb. Jupyter notebooks do not look ok with dark themes.

@ggojedap, to set the theme for Jupyter notebooks add ```"ipynb": "your_theme_name"``` to the value clause of ```"theme-by-language.themes"``` in the  ```settings.json``` file.

![image](https://user-images.githubusercontent.com/48156230/104741981-e7fc7380-576f-11eb-9ce6-f0ca96ac319f.png)

**Comment by ks00x** [comment]
> n issue



> to set the theme for Jupyter notebooks add `"ipynb": "your_theme_name"` to the value clause of `"theme-by-language.themes"` in the `settings.json` file.

This feature is exactly what I am looking for but it does not work for  ipynb files for me. For other files it works well.

**Comment by vhsenna** [comment]
> add `"ipynb": "your_theme_name"` to the value clause of `"theme-by-language.themes"` in the `settings.json` file.

It does not work for ipynb files for me too.

**Comment by jsaulou** [comment]
Closing in favor of #24.
