### ISSUE TITLE
Support for vscode connected to Docker container

### ISSUE THREAD

**Issue by adriantre** [jsaulou/vscode-theme-by-language#9]
Hi, and thanks for this great extension!

Would be great to have support for [development within a docker container](https://code.visualstudio.com/docs/remote/containers). It seems like the extension is unable to find my themes, as the list shows up empty. I guess this is a problem when connecting to a remote with SSH as well.

Cheers!

**Comment by jsaulou** [comment]
The extension uses `vscode.extensions.all` and the `ext.packageJSON.contributes.themes` to list the available themes. it is possible that this does not work in that case. I'll try to see if there is a better way to list themes.

**Comment by virtue3** [comment]
This is also busted when using WSL for presumably the same reason

**Comment by Bravo13** [comment]
Same here. Any updates?

**Comment by jsaulou** [comment]
I had a quick look and the way I get the list of themes does not work for remote development. Unfortunately, I cannot find another way of listing themes.

Anyway, even if I did manage to get the list of themes, it also seems that for remote, the `workbench.colorTheme` setting is not applied for workspace settings. I'm starting to think themes are very 'local' 😄

I may investigate some more but this may not be possible.

**Comment by jsaulou** [comment]
Okay, I investigated some more and it seems setting `extensionKind` to `ui` in the extension's `package.json` is the solution.

Could you try adding this to your user `settings.json` to try it out and tell me if it works for you.

```json
"remote.extensionKind": {
    "jsaulou.theme-by-language": [
      "ui"
    ]
}
```

I tested this with WSL and with a Docker container.
If this works for you too, I'll publish a new version with this set in the extension's `package.json`.

**Comment by adriantre** [comment]
@Bravo13 can you take over from here? I don't use vscode atm.

**Comment by Bravo13** [comment]
Yep, works! Thanks
